### ISSUE TITLE
memray table/tree/flamegraph/summary should accept more than one result argument

### ISSUE THREAD

**Issue by gaborbernat** [bloomberg/memray#115]
## Feature Request

Would be nice if I could do:

```
memray table dump/*.bin
```
instead of 
```
memray table dump/a.bin
memray table dump/a.bin
memray table dump/c.bin
```

**Describe the solution you'd like** A clear and concise description of what you want to happen.
Add any considered drawbacks.

When more than one result is passed evaluate it in a loop.

**Describe alternatives you've considered** A clear and concise description of any alternative
solutions or features you've considered.

Keep requiring 3 calls.

**Teachability, Documentation, Adoption, Migration Strategy** If you can, explain how users will be
able to use this and possibly write out a version the docs. Maybe a screenshot or design?

Feels like by intuition it should just work, so should be easy to teach.

**Comment by pablogsal** [comment]
We have discussed this feature and we have decided to reject it because this is possible to do with a simple shell loop and supporting this in the reporters will add some complexity as some flags like `-o` wouldn't make sense if multiple inputs were given.
