### ISSUE TITLE
Display the stack that generated the memory peak

### ISSUE THREAD

**Issue by gaborbernat** [bloomberg/memray#118]
## Feature Request

When looking at a `flamegraph` and trying to understand when it happens in my application realized I don't really know where the application is in its stack trace when it hits the peek memory usage. It would be great if this could be shown (either part of the HTML or generated separately).

**Comment by gaborbernat** [comment]
Currently, the flame graph tells you the memory usage at peak time. However, without knowing the stack at the peak time I cannot be sure if a given memory allocation should still be around or not. Knowing the stack (state) of the app at the peak time allows me to reason that should this object still be alive? Should it have been already freed up? (if the answer is yes then I can start looking at why and what still keeps a reference to it)

**Comment by pablogsal** [comment]
> However, without knowing the stack at the peak time I cannot be sure if a given memory allocation should still be around or not.

What do you mean? If the allocation appears at peak time *is* around at peak time. The flamegraph shows you what the heap is made of at the time so if you see something is there.

**Comment by godlygeek** [comment]
This doesn't seem to be a common enough need to justify including it in the HTML reports, or providing a command line argument just for this. We have 2 things we want to provide in the future that will address this need, though.

1. We intend to provide an API to our record processing, allowing users to write custom reporters.
2. We intend to provide an interactive web server reporter that allows you to drill down into only the allocations that occurred within a particular time frame.

For now we're going to close this ticket, though, as any work that we do that addresses this request will be done as part of one of those larger initiatives.
