### ISSUE TITLE
Should we have a `memray` entry point?

### ISSUE THREAD

**Issue by godlygeek** [bloomberg/memray#12]
Currently we only have `memray3.X` as an entry point - should we also have `memray`? This will be more confusing for people with multiple copies of `memray` installed, but easier for people with only one, and it would make the usage examples from `-h` line up with how we actually expect it to be used.

**Comment by pablogsal** [comment]
Yeah, I find a bit annoying having to type memray3.x all the time if I am in a virtual environment. So I am +1 on thos
