### ISSUE TITLE
Whether to support Python3.6 ?

### ISSUE THREAD

**Issue by badnotes** [bloomberg/memray#162]

**Comment by godlygeek** [comment]
Can you explain why this would be helpful to you? Python 3.6 has reached end of life and is no longer maintained and no longer receiving security updates, so everyone should be taking the Python 3.6 applications they own and upgrading them to newer versions that are still supported.

**Comment by godlygeek** [comment]
Given that Python 3.6 has reached end of life, we will not pursue this unless there is some extremely compelling justification.
