### ISSUE TITLE
IPython notebook (Jupyter) extension

### ISSUE THREAD

**Issue by ma-sadeghi** [bloomberg/memray#215]
### Is there an existing proposal for this?

- [X] I have searched the existing proposals

### Is your feature request related to a problem?

It'd be nice if we could use `memray` inside a Jupyter notebook (like `memory_profiler`'s `%memit`).

### Describe the solution you'd like

An extension that can be loaded into Jupyter environment so we can memory profile functions, cells, etc.

### Alternatives you considered

`memory_profiler`'s `%memit` magic command.

**Comment by pablogsal** [comment]
Hi @ma-sadeghi and thanks for the proposal :heart: 

We will try to make a prototype and if is not too complex we will likely introduce it in one of the next releases!

**Comment by ma-sadeghi** [comment]
Thank you so much! Looking forward to it!
