### ISSUE TITLE
Allow attachig to a running process

### ISSUE THREAD

**Issue by pablogsal** [bloomberg/memray#218]
It would be great to allow `memray` to attach to a running process and activate profiling on the fly. This will allow users to use the profiler ad-hoc and temporarily attach the profiler to a running process in production environments. Some ideas users will be able to do with this:

* Attach to a running process and force it to dump information into a file for some time.
* Attaching to a running process and activating live mode to inspect what the process is allocating live.
* Activate profiling dynamically in a running server process before sending a specific request to try to reproduce a leak or some kind of memory problem.

**Comment by rkooo567** [comment]
Is this planned to be done next Q? This will be a really useful feature for us (we can use it along with py-spy).

**Comment by pablogsal** [comment]
> Is this planned to be done next Q? This will be a really useful feature for us (we can use it along with py-spy).

Yeah, we have a working prototype and we need to clean it up and polish it.

**Comment by vdwees** [comment]
nice to hear! Not sure what features you have in mind, but I use `py-spy top` to inspect CPU usage of production services. Having an analogous tool for memory would complete my toolkit.
