### ISSUE TITLE
May suppport other platform? (like windows and MacOS)

### ISSUE THREAD

**Issue by WindSoilder** [bloomberg/memray#22]

**Comment by pablogsal** [comment]
Thanks for opening the issue :heart: 

We may look into it in the future, but for the time being is unlikely as we are using quite a a lot of low level Linux-only interfaces to allow us to intercept calls to the allocators at runtime, which is a fundamental part on how `memray` operates. It may be possible to offer `MacOS` support in the future, but I am sure is going to be quite tricky :sweat_smile: . We will announce if we manage to pull it out :)
