### ISSUE TITLE
GPU Memory Tracking

### ISSUE THREAD

**Issue by ax3l** [bloomberg/memray#229]
### Is there an existing proposal for this?

- [X] I have searched the existing proposals

### Is your feature request related to a problem?

Is it possible to extend the tool to track the memory usage of CUDA/HIP/SYCL applications?

GPU acceleration of applications is increasingly common, especially in AI/ML. These operations often come with temporary memory and there is no efficient swap for GPU apps (besides going to host).

### Describe the solution you'd like

Separate tracking for GPU device memory usage :)

**Comment by pablogsal** [comment]
Hi @ax3l and thank you for your issue.

At the time, is very unlikely that we will add support for GPU memory tracking. The reasons are the following:

* APIs to query device memory are global in most cases. This means that is not easy to separate per PID which makes the statistic almost worthless. Also, we would need to implement different APIs for different vendors.
* Testing GPU code on CI is quite complicated and will make maintaining the package much more difficult.
* We would also need to cover a huge amount of existing tests and edge cases including GPU code, which is a considerable amount of work and maintenance.
* We also support macOS so we would also need to add support for [Metal](https://developer.apple.com/metal/) to get feature parity and we don't have enough experience with that at the time.

So, unfortunately, for the time being, I am afraid that we will need to reject this issue as we won't be implementing this soon.

In any case, thanks a lot for the proposal and for using memray ❤️
