### ISSUE TITLE
Reimplement the live TUI using textual

### ISSUE THREAD

**Issue by pablogsal** [bloomberg/memray#238]
https://github.com/Textualize/textual is already a mature enough project with a stable API that we can leverage. We can port or bespoke TUI using `rich` to textual to offer a much better user experience with mouse support, animations, themes, more performant tables and more!

**Comment by pablogsal** [comment]
Oh, that's fantastic! Is not a small feat, be advised (is also not terribly difficult)! 

Feel free to ask us any questions you have.

Regarding textual I'm sure @willmcgugan will be happy to answer questions if he founds some time in his busy schedule :)

**Comment by willmcgugan** [comment]
I would be delighted to help. You might want to jump on the Discord server. https://discord.com/invite/Enf6Z3qhVr
