### ISSUE TITLE
Converting the output of summary reporter to csv/table/dataframe

### ISSUE THREAD

**Issue by sandeepkadapa** [bloomberg/memray#239]
### Is there an existing proposal for this?

- [x] I have searched the existing proposals

### Is your feature request related to a problem?

When there are a lot of allocations in the code, due to certain libraries like tensorflow or sklearn or pandas imported inside the code. The number of allocations goes to several thousand easily and the summary reporter isn't helpful in situations like this as the number of rows to display will be really high and is not easy to analyze.

### Describe the solution you'd like

So, if we convert summary reporter or any other suitable reporter output to a csv/table/dataframe that can be analyzed later with the help of pandas or any data manipulation libraries will be helpful to search and get useful insights. It can also help to profile modules within a big project without trying to profile each and every module individually.

**Comment by pablogsal** [comment]
Thanks a lot @sandeepkadapa for the proposal ❤️ 

In #241 I have implemented a first version that allows the `transform` reporter to dump a CSV file for later analysis. I will try to get this into the next release :)
