### ISSUE TITLE
Add documentation on how to use memray as an API

### ISSUE THREAD

**Issue by pablogsal** [bloomberg/memray#25]
One of our coolest features is being able to use `memray` as an API. We should add documentation:

- [ ] Add API docs with all the relevant classes and enums.
- [ ] Add A tutorial on how to use the `Tracker`, `FileReader` and other utilities.
- [ ] Update the `README`.

**Comment by corleyma** [comment]
Seconding the desire for this.  I'm eager to integrate memray as a profiling option in our python workflow orchestrator, so any guidance on API usage would be a big help.

**Comment by pradyunsg** [comment]
For the folks interested and eager to try things out before @godlygeek has a chance to write down the API docs, you can look at the tests we have, for the public tracking API: https://github.com/bloomberg/memray/blob/main/tests/integration/test_api.py

The `FileDestination` will write to a file, which you can then pass to the various reporters on the CLI to generate the reports. Do make sure that the file passed into the `FileDestination` doesn't exist already. :)
