### ISSUE TITLE
Adding support for Windows

### ISSUE THREAD

**Issue by ht-thomas** [bloomberg/memray#26]
## Feature Request

I tried pip installing Memray on my windows PC but I failed. The error showed that "Memray only supports Linux platforms."
By any chance is there a way of adding support for windows? I'm happy to work on a windows port if it's in the cards (and if I get the hang of the project internals)

**Comment by mkleinbort-ic** [comment]
Hi, I tried installing memray on a Windows PC and it failed with error:

```
RuntimeError: memray does not support this platform (win32)
```

Is this resolved?

**Comment by pablogsal** [comment]
No, it's not. We don't support Windows and it's unlikely that we will ever do. Please check https://bloomberg.github.io/memray/supported_environments.html#supported-operating-systems for more info

**Comment by mkleinbort-ic** [comment]
I saw, thank you
