### ISSUE TITLE
Add how to run with poetry scripts

### ISSUE THREAD

**Issue by knaitas** [bloomberg/memray#27]
Hi, thanks for this tool.

Could you add example on how to run this with poetry CLI scripts?

For example, how I imagined this would work:

```bash
poetry run memray run --live -m make -e file.txt
```

`make` is the poetry CLI command
`-e` some argument
`file.txt` another argument

Is it possible to run it this way right now?

**Comment by pradyunsg** [comment]
@knaitas Could you clarify what you mean by "poetry CLI command"? Are you referring to https://python-poetry.org/docs/pyproject/#scripts?

**Comment by pablogsal** [comment]
I'm closing this issue and there is nothing specific for `memray` to do here. `memray` can be executed as a module as any other Python module that can be executed with `-m`. Unfortunately we don't use poetry ourselves so I suggest to reach the poetry maintainers on how to do that.

**Comment by f4exb** [comment]
Enter first Poetry virtual environment with `poetry shell` then type the usual memray command e.g. `python -m memray run --live <your command with arguments>`

**Comment by brianstewart-cl** [comment]
I got this working by first installing via `poetry add memray` and then (in my case a `flask` app script) running:

`poetry run memray run --live -m flask my-script-name --myarg`
