### ISSUE TITLE
Inverted flame graphs

### ISSUE THREAD

**Issue by godlygeek** [bloomberg/memray#293]
### Is there an existing proposal for this?

- [X] I have searched the existing proposals

### Is your feature request related to a problem?

The [Fil profiler](https://github.com/pythonspeed/filprofiler) has the ability to generate inverted flame graphs. In a normal flame graph, the roots are thread entry points, the children of any given node are the functions called by that node, and the leaf nodes are functions that allocated memory but did not call any functions that allocated memory. This can result in duplicated leaf nodes, if there are multiple call stacks that lead to a particular function that performs allocations. In an inverted flame graph, the roots are the functions that allocated memory, and the children of any given node represent the percentage of any of that node's allocations that can be attributed to a particular caller.

As Fil's documentation describes it:

> The second graph shows the reverse callgraph, from <tt>f()</tt> upwards.</p>
> <p>Why is the second graph useful? If <tt>f()</tt> is called from multiple places, in the first graph it will show up multiple times, at the bottom.
> In the second reversed graph all calls to <tt>f()</tt> will be merged together.</p>

### Describe the solution you'd like

We should implement this idea, as it can sometimes be very helpful in analyzing where memory is being spent in aggregate.

**Comment by gusmonod** [comment]
@ivonastojanovic is taking this with #439. Could you please comment on this issue Ivona so that I can assign it to you?

**Comment by ivonastojanovic** [comment]
Hey, a comment :)
