### ISSUE TITLE
Allow starting the memray tracker without a context manager

### ISSUE THREAD

**Issue by KimiNewt** [bloomberg/memray#296]
### Is there an existing proposal for this?

- [X] I have searched the existing proposals

### Is your feature request related to a problem?

In my code I start a `memray.Tracker` in one function and later have to close it in another. Right now, I have to call `__enter__`/`__close__` manually and that's a bit ugly. It seems like an easy change, but I figured there might be a reason this was made this way.

### Describe the solution you'd like

Change the `__enter__` / `__close__` methods to `enable()` and `disable()` and call those from the contextmanager methods. I can add a PR if necessary.

**Comment by godlygeek** [comment]
This was last discussed in #165. We could always revisit it, but the decision we made at that time was that calling `__enter__` and __exit__` explicitly is a bit ugly, but it's only needed in a relatively rare scenario, and that adding explicit `start` and `stop` methods adds a lot of complexity for how little it buys.
