### ISSUE TITLE
Publish wheel for aarch64

### ISSUE THREAD

**Issue by rossburton** [bloomberg/memray#32]
I went to install memray on my aarch64 box and had to install a load of packages to build it myself.  Please consider also building aarch64 wheels.

**Comment by pablogsal** [comment]
Thanks, @rossburton for opening this issue!

Currently `cibuildwheel` doesn't easily allow us to build `aarch64` wheels, but I think we could manually build something in the interim meanwhile we look for some automated solutions. I know `cibuildwheel` allows some`QEMU` emulation for the wheels but we need time to experiment on that.

In any case, to build from source it should be enough with `libunwind` installed on your box + `pip install memray`.

**Comment by rossburton** [comment]
Sigh, GitHub actions still doesn't have aarch64 runners I see.  https://cibuildwheel.readthedocs.io/en/stable/faq/#emulation does look interesting as a workaround.

**Comment by pablogsal** [comment]
I'm closing this until `cibuildwheel` supports `aarch64`.

**Comment by matthiasdiener** [comment]
Fyi, the memray package in conda-forge (https://github.com/conda-forge/memray-feedstock) has recently gained builds for linux-aarch64 and linux-ppc64le.

**Comment by pablogsal** [comment]
> Fyi, the memray package in conda-forge ([conda-forge/memray-feedstock](https://github.com/conda-forge/memray-feedstock)) has recently gained builds for linux-aarch64 and linux-ppc64le.

Oh, that's very nice! On a note: we **do** have wheels for aarch64 but currently we do them manually unfortunately :(

**Comment by pablogsal** [comment]
Maybe we can do the same for Linux aarch64 using docker on an M1 mac 🤔

**Comment by pablogsal** [comment]
Btw @matthiasdiener would you like to do a PR to advertise the conda forge links in the README? Maybe adding some badges as we do for Pypi or in the installation instructions?

**Comment by matthiasdiener** [comment]
> Maybe we can do the same for Linux aarch64 using docker on an M1 mac 🤔

In my experience, running docker on Mac M1 to run Linux-aarch64 builds works pretty well.

**Comment by matthiasdiener** [comment]
> Btw @matthiasdiener would you like to do a PR to advertise the conda forge links in the README? Maybe adding some badges as we do for Pypi or in the installation instructions?

Sure, let me see if I can come up with something.
