### ISSUE TITLE
programatically convert memray output into flamegraph

### ISSUE THREAD

**Issue by Okroshiashvili** [bloomberg/memray#328]
### Is there an existing proposal for this?

- [X] I have searched the existing proposals

### Is your feature request related to a problem?

I want to use memray api to profile my function programatically.
I managed to write a decorator to profile a function. However, it's really inconvenient to save output in .bin format and then convert it to flamegraph or something else. 

### Describe the solution you'd like

I'd like there to be possibility to programmatically convert memray output (.bin file) into flamegraph and don't spit out .bin file at all.

**Comment by godlygeek** [comment]
> I'd like there to be possibility to programmatically convert memray output (.bin file) into flamegraph and don't spit out .bin file at all.

Can you describe your use case in more detail? Why is having a .bin file inconvenient for you? Would using a temp file for the memray output and then removing it after you create the flamegraph be good enough for your use case?

I'm picturing something like:
```py
import contextlib
import subprocess
import sys
import tempfile

import memray


@contextlib.contextmanager
def memory_flamegraph(destination_file):
    with tempfile.TemporaryDirectory() as tmpdir:
        capture_file = f"{tmpdir}/capture.bin"
        cmd = [
            sys.executable,
            "-m",
            "memray",
            "flamegraph",
            "-f",
            "-o",
            destination_file,
            capture_file,
        ]

        try:
            with memray.Tracker(capture_file):
                yield
        finally:
            subprocess.check_call(cmd)
```

And you'd then use that by doing something like:
```py
with memory_flamegraph("./flamegraph.html"):
    do_thing1()
    do_thing2()
```

**Comment by godlygeek** [comment]
Ah, and you want that as a decorator. I don't think that really changes anything about the code I'm suggesting, though. You'd just update your decorator to call that `memray_flamegraph` context manager instead of the `memray.Tracker` one.

**Comment by Okroshiashvili** [comment]
Thanks @godlygeek for providing example. That will help me a lot 🙏
