### ISSUE TITLE
Jupyter magic %%memray_flamegraph text output hardly readable in dark theme

### ISSUE THREAD

**Issue by EtiennePelletier** [bloomberg/memray#343]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The %%memray_flamegraph output file name and progress bar status use the [blue](https://rich.readthedocs.io/en/stable/appendix/colors.html) font color, which is very difficult to see in Jupyterlab's dark theme. ([ref 1](https://github.com/bloomberg/memray/blob/main/src/memray/_ipython/flamegraph.py#L162), [ref 2](https://github.com/bloomberg/memray/blob/main/src/memray/_memray.pyx#L801))

![memray_jupyterlab_dark](https://user-images.githubusercontent.com/16963011/233472892-fe2ed5ca-03e1-4153-9340-0de0e3d3d6e4.png)

In light theme, it is fine.
![memray_jupyterlab_light](https://user-images.githubusercontent.com/16963011/233472906-46014fa8-649b-49c0-9fe0-c821ca857929.png)

### Expected Behavior

For best accessibility, output text should be readable easily in both themes.
In this case, a lighter blue variant such as `dodger_blue1` or `deep_sky_blue1` would be a better fit:
![color_comparison](https://user-images.githubusercontent.com/16963011/233478910-3e8c49e6-79f5-4876-b06f-36c9c058d706.png)

### Steps To Reproduce

1. Use dark theme in Jupyterlab
2. Load and use the %%memray_flamegraph cell magic or simply run the following:
```python
import rich
rich.print('[blue]Can you read this?')
```

### Memray Version

1.7.0

### Python Version

3.10

### Operating System

Linux

### Anything else?

I would be happy to contribute a change for this but did not want to decide what color to pick by myself.

**Comment by godlygeek** [comment]
Thanks for the heads up about this! I don't think we depend upon the terminal being 256-color as things stand today, so I'd rather not change these to `dodger_blue1` or `deep_sky_blue1`, or anything else with a number above 15.

As an alternative, changing these both to `cyan` looks pretty good to me, under both JupyterLab themes as well as in my terminal. Do you agree that looks nice? If so, I'd happily accept a PR!

**Comment by EtiennePelletier** [comment]
This sounds good!
