### ISSUE TITLE
Use `ruff` instead of `flake8` and `isort`

### ISSUE THREAD

**Issue by godlygeek** [bloomberg/memray#346]
https://github.com/charliermarsh/ruff is an extremely fast Python linter with built in caching. Switch our `make lint` and `make format` commands to run `ruff` instead of `flake8` and `isort`.

**Comment by flpm** [comment]
I am looking into this issue

**Comment by gusmonod** [comment]
The PR above fixes this issue.

**Comment by gusmonod** [comment]
Thank you @flpm !
