### ISSUE TITLE
Set up CI to build and test musl libc wheels

### ISSUE THREAD

**Issue by godlygeek** [bloomberg/memray#352]
Currently `pystack` publishes `musllinux` wheels, but `memray` doesn't. Update our GitHub Actions to build, test, and publish `musllinux` wheels.

**Comment by salticus** [comment]
I would like to try this issue today.

**Comment by gusmonod** [comment]
Closed by the above PR. Thanks @salticus !

**Comment by salticus** [comment]
You're welcome!
