### ISSUE TITLE
Copy "Contribution Licensing" section from README to CONTRIBUTING

### ISSUE THREAD

**Issue by godlygeek** [bloomberg/memray#357]
Copy the https://github.com/bloomberg/memray#contribution-licensing section of the README.md into the CONTRIBUTING.md to make it more discoverable for future contributors.

It should be added to the https://github.com/bloomberg/memray/blob/main/CONTRIBUTING.md#pull-requests section.

**Comment by stefmolin** [comment]
I'll take this one.
