### ISSUE TITLE
Flamegraph view gets stuck 

### ISSUE THREAD

**Issue by mgmacias95** [bloomberg/memray#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I made this simple script to test the new temporary flamegraphs feature:
```python
import random
import string
from collections import Counter

def set_up():
  b = random.choice(string.ascii_letters)
  return Counter(b)

def run():
  c = set_up()
  key = random.choice(list(c.keys()))
  print(f'{key}: {c[key]}')


run()
```

I executed the following commands:
```shellsession
$ python -m memray run test.py                                   
Writing profile results into memray-test.py.73578.bin
o: 1
[memray] Successfully generated profile results.

You can now generate reports from the stored allocation records.
Some example commands to generate reports:

/Users/mgmacias/Documents/GitHub/memray/env/bin/python -m memray flamegraph memray-test.py.73578.bin
$ python -m memray flamegraph memray-test.py.73578.bin --temporal 
Wrote memray-flamegraph-test.py.73578.html
```

Then opened the flamegraph on my chrome browser. The flamegraph gets stuck on this loading view:
<img width="1505" alt="image" src="https://github.com/bloomberg/memray/assets/8604906/1ec596cc-81b8-4796-a814-d252c6aebdfd">

When checking the chrome dev console I can see the following error message:
<img width="551" alt="image" src="https://github.com/bloomberg/memray/assets/8604906/314ad9b8-ef38-4215-a643-ace1ceab5e23">

### Expected Behavior

An error message or a flamegraph.

### Steps To Reproduce

1. Save the script to a python file
2. Run the commands mentioned above
3. Open the flamegraph in chrome

### Memray Version

1.8.0

### Python Version

3.11

### Operating System

macOS

**Comment by pablogsal** [comment]
There are two possible problems that this bug surfaces:

* Is possible that the script runs so fast that the two ends of the graph are the same.
* If the memory is flat the high the `hwmBytes` is somehow `undefined`.

**Comment by pablogsal** [comment]
This seems to happen because in this case `high_water_mark_by_snapshot` is an empty array.

**Comment by pablogsal** [comment]
I think at the very least this:

https://github.com/bloomberg/memray/blob/c2c8d53393de25670a9da0325c34027a7ed4c015/src/memray/reporters/assets/temporal_flamegraph.js#L55

should be

```
  if (hwms && hwms.length > 0) {
```

**Comment by pablogsal** [comment]
I think this is enough to fix it:

```diff
diff --git a/src/memray/reporters/assets/temporal_flamegraph.js b/src/memray/reporters/assets/temporal_flamegraph.js
index d43a509..259e5f0 100644
--- a/src/memray/reporters/assets/temporal_flamegraph.js
+++ b/src/memray/reporters/assets/temporal_flamegraph.js
@@ -52,7 +52,7 @@ function packedDataToTree(packedData, rangeStart, rangeEnd) {
   }

   const hwms = packedData.high_water_mark_by_snapshot;
-  if (hwms) {
+  if (hwms && hwms.length > 0 && memory_records.length > 0) {
     console.log("finding highest high water mark in range");
     let hwmSnapshot = rangeStart;
     let hwmBytes = hwms[rangeStart];
```
