### ISSUE TITLE
Ignore specified packages or paths

### ISSUE THREAD

**Issue by rossjp** [bloomberg/memray#40]
## Feature Request

**Is your feature request related to a problem? Please describe.**

The `memray` output can be somewhat cluttered by data that I'm not interested in.

![image](https://user-images.githubusercontent.com/794254/164552369-0e22fb9a-c0ab-49ba-a895-bea93b725617.png)

**Describe the solution you'd like** A clear and concise description of what you want to happen.

Provide a flag that would allow a user to supply a list of packages and/or paths to exclude from `memray`'s analysis/reporting. In the above scenario, it would be great to tell `memray`, either through a value provided on the command line, or a pointer to a manifest file with a list of things to ignore, that I don't want it to tell me about `gunicorn` memory usage. Or potentially anything under `/usr/local/lib/python3.7/site-packages/`. This flag could be invoked either during `memray run` or `memray <reporter>` commands (or both).

**Describe alternatives you've considered**

Using `grep` (or similar tool). E.g.,:
`root@28689a9cb754:/usr/src/app# memray3.7 summary memray.out.10 | grep -v gunicorn`

This kinda works for some reporters, but the fidelity of the output is lost a bit. Notably, it also does not work for the flamegraph option.

![image](https://user-images.githubusercontent.com/794254/164553434-eea9a470-5ef3-4746-a14f-f04014068234.png)

**Teachability, Documentation, Adoption, Migration Strategy** If you can, explain how users will be
able to use this and possibly write out a version the docs. Maybe a screenshot or design?

`root@28689a9cb754:/usr/src/app# memray3.7 summary --ignore-package gunicorn memray.out.10`
or
`root@28689a9cb754:/usr/src/app# memray3.7 summary --ignore-path /usr/local/lib/python3.7/site-packages/ memray.out.10`
or
`root@28689a9cb754:/usr/src/app# memray3.7 summary --ignore-manifest manifest.txt memray.out.10`
```
root@28689a9cb754:/usr/src/app# cat manifest.txt
foo
bar
gunicorn
/usr/local/lib/python3.7/
```

**Comment by godlygeek** [comment]
> Notably, it also does not work for the flamegraph option.

For the feature you're imagining, would you like it to prune entire branches off the tree of calls, or just collapse intermediate subtrees?

Let's imagine our code had:

```py
# in a.py
from b import b
def a(n):
    return b(n)
```
```py
# in b.py
from c import c
from d import d
def b(n):
    return [c(n), d(n)]
```
```py
# in c.py
def c(n):
    return "a" * n
```
```py
# in d.py
def d(n):
    return "a" * n
```
```py
# in main.py
from a import a
a(100000)
```

Currently, the flame graph generated from a run of `main.py` looks like this:
```
+---+---+
| c | d |
+---+---+
|   b   |
+-------+
|   a   |
+-------+
```
And it will show that `a` and the things it called were responsible for around 200kb of allocations, `b` and the things it called were responsible for around 200kb of allocations, and each of `c` and `d` were responsible for around 100kb of allocations.

If we ran the tool and said `--ignore-package b`, what would you expect to see?

**Comment by godlygeek** [comment]
It's not obvious how such a feature could or should work, and there has been no response from the requester. Closing this for lack of demand.
