### ISSUE TITLE
AGGREGATED_ALLOCATIONS for process attach?

### ISSUE THREAD

**Issue by leiwen83** [bloomberg/memray#405]
### Is there an existing proposal for this?

- [X] I have searched the existing proposals

### Is your feature request related to a problem?

Some long running process may encounter sudden memory surf at unclear time point, so it would helps a lot it memray could attach to some abnormal process and use AGGREGATED_ALLOCATIONS mode.

### Describe the solution you'd like

Since AGGREGATED_ALLOCATIONS mode would help reduce the long running process recording size, and current limitation is it shall be written when recording is off. Then how about set kind of signal receive mechanism, or socket?, so that outsider could notify AGGREGATED_ALLOCATIONS recording gracefully shutdown itself?

**Comment by pablogsal** [comment]
Fixed by https://github.com/bloomberg/memray/pull/455
