### ISSUE TITLE
Publish ARM Linux Wheels

### ISSUE THREAD

**Issue by ginevragaudioso** [bloomberg/memray#428]
### Is there an existing proposal for this?

- [X] I have searched the existing proposals

### Is your feature request related to a problem?

Not related to a problem.

### Describe the solution you'd like

Could you consider building and publishing wheels for Linux ARM? From what I can tell, these are not being published. Thanks!

### Alternatives you considered

Currently, pip figures out the wheel is not there, and it builds the code. This today failed for https://github.com/bloomberg/memray/issues/426, so there could be build failures that happen. Even when it does work, it is slow to build instead of using a pre-made wheel.

**Comment by pablogsal** [comment]
Hi @ginevragaudioso! We are going to publish aarch64 wheels in the next release thanks to https://github.com/bloomberg/memray/pull/416
