### ISSUE TITLE
Crashes while processing large output binary

### ISSUE THREAD

**Issue by delica1** [bloomberg/memray#43]
We have an application which uses a lot of memory > 30GB and we're trying to understand where the memory is used. The output binary file is 150GB+ and when try to create a table /HTML / summary it crashes with out of memory errors because it seems to try to process the entire large file in memory at once.

**Comment by godlygeek** [comment]
Well, that's a fun stress test. Yeah, I'm guessing that the `d_allocation_records.reserve(stats.n_allocations);` call in `RecordReader::RecordReader` is failing due to the large number of allocated records.

So... we'll have to see what can be done about that.

**Comment by godlygeek** [comment]
If you still have that file, would you kindly mind running:
```
memray parse output.new.bin | awk '{print $1}' | sort | uniq -c
```
for me?

That'll read the output file and give us a count of different types of records in it. (`memray parse` is a (currently) undocumented command that pretty-prints the contents of a binary capture file as plain text; there are no guarantees about its format remaining stable across releases, it is meant as a debugging tool.)

I'm curious exactly how many allocations we're dealing with here.

**Comment by godlygeek** [comment]
I wouldn't be shocked if `memray run` takes several minutes to run on a 150 GB file, either.

**Comment by delica1** [comment]
took about 2.5 hours :)

2546564914 ALLOCATION
  19631 FRAME_ID
820219592 FRAME_POP
862137699 FRAME_PUSH
      1 HEADER
 174981 MEMORY
      1 THREAD

**Comment by godlygeek** [comment]
A new version was released yesterday that both writes smaller output files and doesn't attempt to load all allocation records into memory simultaneously. Give Memray 1.1.0 a shot (`pip install --upgrade memray` if you're using `pip`) and see if things work better for you now.

**Comment by rski** [comment]
I have a 50mb binary file, doing memray flamegraph on it always crashes like this:

```
read(4, "\"\"\"\nRead and write ZIP files.\n\nX"..., 8192) = 8192
close(4)                                = 0
write(2, "    import binascii\n", 20    import binascii
)   = 20
write(2, "ImportError: /usr/lib64/python3."..., 152ImportError: /usr/lib64/python3.9/lib-dynload/binascii.cpython-39-x86_64-linux-gnu.so: failed to map segment from shared object: Cannot allocate memory
) = 152
rt_sigaction(SIGINT, {sa_handler=SIG_DFL, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f62c55891d0}, {sa_handler=0x7f62c5b383a0, sa_mask=[], sa_flags=SA_RESTORER, sa_restorer=0x7f62c55891d0}, 8) = 0
close(3)                                = 0
``

The stats on the file:
```
1489816 ALLOCATION
1692761 ALLOCATION_WITH_NATIVE
     13 CONTEXT_SWITCH
  43983 FRAME_ID
 467304 FRAME_POP
1201472 FRAME_PUSH
      1 HEADER
    508 MEMORY_MAP_START
  29530 MEMORY_RECORD
 726660 NATIVE_FRAME_ID
 767850 SEGMENT
 382909 SEGMENT_HEADER
      1 THREAD
```

This is with v1.1.0, the patches above are included. 

I ran memray on memray flamegraph to see if anything interesting pops up, once it finishes I'll try to provide any interesting information here. I'll also try to build memray from master and see if that helps at all.

**Comment by godlygeek** [comment]
Would you mind opening a new issue for that? Whatever is causing your

> ImportError: /usr/lib64/python3.9/lib-dynload/binascii.cpython-39-x86_64-linux-gnu.so: failed to map segment from shared object: Cannot allocate memory

It's definitely a distinct issue from this one. Can you try to figure out some steps to reproduce the issue?

**Comment by rski** [comment]
sure, will do once I get some more info
