### ISSUE TITLE
Support --follow-fork

### ISSUE THREAD

**Issue by slannez-fico** [bloomberg/memray#448]
### Is there an existing proposal for this?

- [X] I have searched the existing proposals

### Is your feature request related to a problem?

I have an issue when I want to profile memory consumption over programs based on multiprocessing.

### Describe the solution you'd like

I would love if the plugin could accept a "--follow-fork" argument like "memray run"

### Alternatives you considered

Using "with memray.Tracker(file_name=..., follow_fork=True)" in the instrumented app, but that kind of defeat the purpose of using a general purpose pytest plugin...

**Comment by pablogsal** [comment]
Duplicate of https://github.com/bloomberg/pytest-memray/issues/89
