### ISSUE TITLE
CLI ignores -o

### ISSUE THREAD

**Issue by adrinjalali** [bloomberg/memray#46]
## Bug Report

CLI ignores `-o` and writes to a different output

```bash
$ memray run benchmarks/bench_feature_expansions.py -o /tmp/bench.bin
Writing profile results into benchmarks/memray-bench_feature_expansions.py.83352.bin
...
[memray] Successfully generated profile results.

You can now generate reports from the stored allocation records.
Some example commands to generate reports:

/path/to/.venv/bin/python -m memray flamegraph benchmarks/memray-bench_feature_expansions.py.83352.bin

```

It should instead write into the specified `/tmp/bench.bin`

**Environment**

- python=3.10
- memray=1.0.3

**Comment by pablogsal** [comment]
The CLI is not ignoring `-o` is just that you are passing `-o` to your script!

For this to work you need to pass all `memray`-related configurations after `run` but before your script:

```
memray run -o /tmp/bench.bin benchmarks/bench_feature_expansions.py 
```

Why is that? This is so if your script takes arguments you can call it normally. For instance:

```
memray run -o /tmp/bench.bin benchmarks/bench_feature_expansions.py --my-script-argument --not-a-memray-arg --expansions=12
```

I'm closing this, but feel free to reopen if we missed anything!
