### ISSUE TITLE
MacOS Sonoma: SIGBUS errors

### ISSUE THREAD

**Issue by tsiq-karold** [bloomberg/memray#476]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I've been using memray this week to profile one of our apps and it has been tremendously helpful.  Earlier today, I upgraded my Mac to Sonoma and I'm no longer able to profile this project.  It crashes with a SIGBUS error:
```
Process finished with exit code 138 (interrupted by signal 10: SIGBUS)
```

Nothing has changed between it working and crashing, other than the MacOS upgrade.  II tried just plain run and also live, both crash.  I have also tried profiling a test Python script but that isn't crashing.  So clearly something doesn't like something our app is doing but I'm not sure what the best way would be to try and debug this.  Any suggestions welcome.

### Expected Behavior

I'm able to successfully profile on MacOS Sonoma.

### Steps To Reproduce

I tried creating a small reproducible example but I've not yet managed it.

### Memray Version

1.9.1

### Python Version

3.9

### Operating System

macOS

**Comment by pablogsal** [comment]
I tried in macOS Sonoma and I can run the test suite without problems. Do you have a reproducer I can execute?

**Comment by pablogsal** [comment]
Maybe can you also provide a stack trace with lldb?

**Comment by pablogsal** [comment]
That seems to be only one frame, can you run "bt" to show all frames in the stack?

**Comment by pablogsal** [comment]
Ugh, that looks like a stackoverflow :(

How are you getting Python 3.9?

**Comment by tsiq-karold** [comment]
With pyenv

**Comment by pablogsal** [comment]
I can try to give you a version of memray to check if it fixes this. 

Can you confirm you can compile memray in your machine? (Build instructions are in the README)

**Comment by tsiq-karold** [comment]
> I can try to give you a version of memray to check if it fixes this. 
> 
> Can you confirm you can compile memray in your machine? (Build instructions are in the README)

I've never built it but I'll try it out this evening.

Thanks for the help and fast responses!

**Comment by pablogsal** [comment]
In any case I think we still need a reproducer to be able to understand how this is happening.

**Comment by pablogsal** [comment]
Can you check that memray from this branch crashes or works?

https://github.com/pablogsal/memray/tree/dlyd4

To build:

```
git clone https://github.com/pablogsal/memray.git
cd memray
git checkout dlyd4
brew install lz4
export CFLAGS="-I$(brew --prefix lz4)/include" LDFLAGS="-L$(brew --prefix lz4)/lib"
# Ensure you uninstall any memray in your venv first!
python -m pip install .
```

**Comment by pablogsal** [comment]
@tsiq-karold are you by any chance using the pyobjc library in your app?

**Comment by tsiq-karold** [comment]
I'm still trying to narrow things down to a reproducible test that I can share.

I tried that branch and it still crashes with an identical looking stack.  I also tried with a slightly modified version of your branch so I could be 100% it was using that version; my modification was simply to print the `image_name` and right before the crash it's definitely not showing anything resembling the names in that if statement.

We do not use pyobjc, no.

**Comment by pablogsal** [comment]
> I'm still trying to narrow things down to a reproducible test that I can share.
> 
> 
> 
> I tried that branch and it still crashes with an identical looking stack.  I also tried with a slightly modified version of your branch so I could be 100% it was using that version; my modification was simply to print the `image_name` and right before the crash it's definitely not showing anything resembling the names in that if statement.
> 
> 
> 
> We do not use pyobjc, no.

Could you paste here all the image_name values that happen before it crashes?

**Comment by pablogsal** [comment]
Meanwhile a way to narrow that is the following:

For every image_name, add a similar line as the one y added and check that doesn't crash. Then uncomment line by line until it crashes again. This can be done as binary search. Then tell us the library that makes it crash

**Comment by pablogsal** [comment]
Can you try also the last commit in:

https://github.com/pablogsal/memray/tree/dlyd4

(https://github.com/pablogsal/memray/commit/dd30b6571283129d27409a821c7912adb8b5a470)

**Comment by tsiq-karold** [comment]
> Could you paste here all the image_name values that happen before it crashes?

This is the list as it gets printed out.  There's a lot of duplication in there but I thought I'd leave it as is in case the order matters.

[image_names.log](https://github.com/bloomberg/memray/files/12814275/image_names.log)

**Comment by tsiq-karold** [comment]
> python -m pip install .

No crashes with this commit!!

**Comment by tsiq-karold** [comment]
> Can you try also the last commit in:
> 
> https://github.com/pablogsal/memray/tree/dlyd4
> 
> ([pablogsal@dd30b65](https://github.com/pablogsal/memray/commit/dd30b6571283129d27409a821c7912adb8b5a470))

No crashes with this commit!!

**Comment by pablogsal** [comment]
Ok that's fantastic to know. We can try to trim that a bit. Can you try to change the conditional to:

strstr(image_name, "/usr/lib/") || strstr(image_name, "/System/")

And check if it crashes?

**Comment by tsiq-karold** [comment]
Do you mean the conditional that you modified in your first commit or the one from the second commit?

**Comment by tsiq-karold** [comment]
I did this:
```
                if (strstr(image_name, "/usr/lib/") || strstr(image_name, "/System/")) {
                    patch_stubs(section, slide, dyninfo_table, restore_original);
                }
```
and it started crashing again.

**Comment by pablogsal** [comment]
Can you try the following to see if it crashes (each separately):

strstr(image_name, "System/Library/PrivateFrameworks")

strstr(image_name, "System/Library/Frameworks")

strstr(image_name, "Services")

**Comment by tsiq-karold** [comment]
I've been doing something along the lines to narrow it down, will report once I find the culprit

**Comment by tsiq-karold** [comment]
OK, with this line in:
```
                if (strstr(image_name, "/usr/lib/") || strstr(image_name, "/System/Library/Frameworks/")
		    ...
		    || strstr(image_name, "/System/Library/PrivateFrameworks/MallocStackLogging.framework")
		    ...
		    ) {
                    patch_stubs(section, slide, dyninfo_table, restore_original);
                }
```
It crashes.  Commenting out the `/System/Library/PrivateFrameworks/MallocStackLogging.framework` runs without crashing.

**Comment by tsiq-karold** [comment]
I should add that from everything in /System/Library, only PrivateFrameworks/MallocStackLogging.framework causes trouble.  I'll try the other things you suggested.

**Comment by tsiq-karold** [comment]
No crashes with this:
```
                if (!strstr(image_name, "/System/Library/PrivateFrameworks/MallocStackLogging.framework")) {
                    patch_stubs(section, slide, dyninfo_table, restore_original);
                }
```

**Comment by pablogsal** [comment]
Hummm I am confused, shouldn't my first commit in the branch cover that:

https://github.com/pablogsal/memray/commit/a7e1ad6b8a640ea8abf11bd6dd15d0e23b5b9d8e

**Comment by tsiq-karold** [comment]
Apologies, I suspect this may have been user error... I just updated my local clone of your branch to effectively be your first commit and it's not crashing.  It's also not crashing when making it more tightly scoped, i.e.:
```
        if (strstr(image_name, "/System/Library/PrivateFrameworks/MallocStackLogging.framework") || strstr(image_name, "libdyld.dylib") || strstr(image_name, "/usr/lib/system/")) {
            std::cout << "Skipping patching image: " << image_name << std::endl;
            LOG(DEBUG) << "Skipping patching image: " << image_name;
            continue;
        }
```

**Comment by pablogsal** [comment]
Fantastic! This is enough for us to do a fix. We will release a new version with the fix shortly 😉

In the meantime you can hopefully use the custom memray build you have with the fix to profile your applications in the meantime :)

Btw, if you have some time it would be fantastic if you can leave a comment with your experience using memray in here:

https://github.com/bloomberg/memray/discussions/226

It really helps!

**Comment by pablogsal** [comment]
For the record, the problem is that apple has a debug malloc library that enables hooks that take snapshots of the stack in demand in that library:

https://developer.apple.com/library/archive/documentation/Performance/Conceptual/ManagingMemory/Articles/MallocDebug.html

These custom hooks make the system libraries interfere with memray because both are trying to patch malloc in incompatible ways. As apple has an advantage over memray, they can patch some system pointers that we cannot and forces us to not be able to stop recursion when the memray thread local variables are initialised.

The solution is basically not mess with that library from memray to avoid interfering.

The crash only happens if you are using something that ends needing to link to the system framework libraries that can use that capability, that's why you are only seeing the crash in your application and not on other python scripts.

**Comment by tsiq-karold** [comment]
Awesome, thanks. Yes, I can work with this for now.

Thank you for the timely help.
