### ISSUE TITLE
--leaks flag used as module argument

### ISSUE THREAD

**Issue by mrks-g** [bloomberg/memray#514]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Starting memray with the --leaks option does not work as expected on wsl2. 
`python3 -m memray run -m server.start --leaks`

the leaks-option is interpreted as a module attribute to server.start. How to use this option correctly? 

### Expected Behavior

I expected memray to start with the --leaks option.

### Steps To Reproduce

ubuntu 22.04
python3 -m pip install memray
python3 -m memray run -m server.start --leaks

### Memray Version

1.11.0

### Python Version

3.10

### Operating System

Linux

**Comment by godlygeek** [comment]
It needs to go before the `-m`, as everything after that is taken as the module to run and the arguments for that module.

```sh
python3 -m memray run --leaks -m server.start
```

**Comment by mrks-g** [comment]
Did not mentioned that I tried this already. The result is a unrecognized argument error: 
`memray: error: unrecognized arguments: --leaks`

**Comment by godlygeek** [comment]
Oh, my bad. Arguments to `memray run` do need to go before the `-m`, but `--leaks` is an argument for the reporter you're using, not for `memray run`

So, something like:
```sh
python3 -m memray run --trace-python-allocators -o output.bin -m server.start
python3 -m memray flamegraph --leaks output.bin
```
