### ISSUE TITLE
is memray support profiling c version of python package like pillow?

### ISSUE THREAD

**Issue by zdyj3170101136** [bloomberg/memray#526]
is memray support profiling c version of python package like pillow?

**Comment by godlygeek** [comment]
Yes, see https://bloomberg.github.io/memray/run.html#native-tracking - you'll need to use the `--native` option to `memray run`, and you'll need to generate the reports on the same machine the capture file was generated on.

**Comment by zdyj3170101136** [comment]
> Yes, see https://bloomberg.github.io/memray/run.html#native-tracking - you'll need to use the `--native` option to `memray run`, and you'll need to generate the reports on the same machine the capture file was generated on.

[memray-flamegraph-benchmakr.py.13823.html.zip](https://github.com/bloomberg/memray/files/13985968/memray-flamegraph-benchmakr.py.13823.html.zip)

here is my memory profiling.

i read a lot of image:
```
import os
import PIL
from PIL import Image

dir = "/home/centos/pillow-bench/Images_0/0"
onlyfiles = []

filedir = dir
files = [f for f in os.listdir(filedir) if os.path.isfile(os.path.join(filedir, f))]
filepaths = map( lambda x: os.path.join(filedir, x), files )
onlyfiles += list(filepaths)

s = 0
for i in range(len(onlyfiles)):
    fname = onlyfiles[i]
    image = PIL.Image.open(fname)
    # Do something
    image.tobytes("xbm", "rgb")
    if i % 10000 == 0:
        print('iteration ', i)

input("Press Enter to continue...")
```

i expect there have lots of memory allocation by pillow package, but there is not.
