### ISSUE TITLE
Please activate the `Discussions` tab 

### ISSUE THREAD

**Issue by sugatoray** [bloomberg/memray#53]
## Feature Request

GitHub Discussions help open-source repositories maintain various types of discussions separately from the issues. Also, it is very easy to create an issue from a discussion topic. Please activate the discussions feature on this repository.

- [Quickstart for GitHub Discussions](https://docs.github.com/en/discussions/quickstart)

![image](https://user-images.githubusercontent.com/10201242/164844912-542d83a1-6a6f-4cfd-85af-fa177c97cbe3.png)

**Comment by sugatoray** [comment]
### I wanted to add the following as a discussion (since it is neither a bug, or a feature request)

One more thing: `memray` is now available on conda-forge thanks to @matthiasdiener.

Install with conda:

```sh
conda install -c conda-forge memray
```

[![image](https://user-images.githubusercontent.com/10201242/164844293-6a021a9d-2497-4b31-b3ff-6752c2fdbe9e.png)](https://anaconda.org/conda-forge/memray)

**Comment by sugatoray** [comment]
cc: @godlygeek @pablogsal

**Comment by pablogsal** [comment]
@sugatoray Thanks a lot for the suggestion! I have opened and configured the tab here:

https://github.com/bloomberg/memray/discussions

**Comment by pablogsal** [comment]
> One more thing: `memray` is now available on conda-forge thanks to @matthiasdiener.

Nice, this is fantastic ❤️ 

Thanks a lot @matthiasdiener and @sugatoray !
