### ISSUE TITLE
Ctrl-Z in "memray tree" doesn't work

### ISSUE THREAD

**Issue by kshpytsya** [bloomberg/memray#559]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

It is impossible to use `Ctrl-Z` to background the "memray tree" TUI.

### Expected Behavior

I would like to be able to use the standard `Ctrl-Z` to send memray's TUI to background.

### Steps To Reproduce

1. Obtain some memray tracker run results
2. Run `memray tree <file>` in terminal
3. Press `Ctrl-Z`

Actual behavior: `Ctrl-Z` press is ignored.
Expected behavior: memray's TUI is sent to background and I see shell prompt.

### Memray Version

1.11.0

### Python Version

3.8, 3.11

### Operating System

Linux

**Comment by willmcgugan** [comment]
ctrl+z to suspend isn't enabled by default, but you can [add it with a keybinding](https://textual.textualize.io/guide/app/#suspending-from-foreground). 

This is relatively new, so likely didn't exist when you built your TUI.
