### ISSUE TITLE
How to profile gunicorn workers?

### ISSUE THREAD

**Issue by TheCodeYoda** [bloomberg/memray#579]
my startup command looks like this
```
gunicorn --workers 2 -k uvicorn.workers.UvicornWorker my_server.main:server --bind '0.0.0.0:8000' --access-logfile - --error-logfile - --log-level info
```
How do I profile this using memray? is there a way to use the cli with this startup command?

**Comment by dilshans2k** [comment]
Hey can you share the cli command used?

I am running uvicorn server, but i don't think it will be any different compared to guvicorn.
`uvicorn score:app --reload --log-config ../log.ini`
