### ISSUE TITLE
Flame graph time axis offset (perhaps due to timezone)

### ISSUE THREAD

**Issue by braingram** [bloomberg/memray#591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I generated a profile and flamegraph on a remote machine (that uses UTC). The flamegraph page `stats` include:
```
Start time: 2024-05-03 12:35:24.695000
End time: 2024-05-06 02:40:31.130000
```
However, when I view the page on my laptop (ET) the first point on the graph reports a time of `May 3rd, 2024, 08:35`.

Is there an option to set maybe the timezone of the graph so it will match the times reported in the `stats` (and in my case times from other logs generated by the program, which are all in the system UTC time)?

Thanks and let me know if any more information is helpful. Also, memray is awesome :)

### Steps To Reproduce

I think this could be reproduced by generating a log on a system using UTC then viewing it on a system uses a different timezone.

### Memray Version

1.12.0

### Python Version

3.12

### Operating System

Linux

**Comment by vitimm144** [comment]
I can try to help on this issue
