### ISSUE TITLE
memray attach PID -o FILE returns Permission Denied

### ISSUE THREAD

**Issue by xtrusia** [bloomberg/memray#653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

sudo memray attach 662 -o p
Failed to start tracking in remote process: OSError('Could not create output file /home/ubuntu/p: Permission denied')

### Expected Behavior

It writes proper information to specified file as document says.

### Steps To Reproduce

sudo memray attach PID -o FILE

### Memray Version

1.13.4

### Python Version

3.10

### Operating System

Linux

**Comment by godlygeek** [comment]
Sorry for the late reply, I somehow totally missed this issue!

I'm not sure what would cause this issue, but I doubt it's a Memray issue...

Does the file `/home/ubuntu/p` already exist? If so, what does `getfattr -d -m '' -- /home/ubuntu/p` report? If not, does `sudo touch /home/ubuntu/p` succeed, or does it also fail with a permission denied error?

**Comment by xtrusia** [comment]
Hey @godlygeek 
Thanks for the comment. 
Unfortunately, I still get the same error.


ubuntu@node-01:~$ sudo touch /home/ubuntu/p
ubuntu@node-01:~$ sudo memray attach 9820 -o p
Failed to start tracking in remote process: OSError('Could not create output file /home/ubuntu/p: Permission denied')

**Comment by godlygeek** [comment]
So the file does already exist. What does this report?
```sh
getfattr -d -m '' -- /home/ubuntu/p
```

Do you see the same error if you
```sh
sudo mv /home/ubuntu/p /home/ubuntu/q
sudo memray attach 9820 -o p
```

**Comment by xtrusia** [comment]
hey

`
ubuntu@node-01:~$ ls
p
ubuntu@node-01:~$ getfattr -d -m '' -- /home/ubuntu/p
ubuntu@node-01:~$ sudo mv /home/ubuntu/p /home/ubuntu/q
ubuntu@node-01:~$ sudo memray attach 9820 -o p
Failed to start tracking in remote process: OSError('Could not create output file /home/ubuntu/p: Permission denied')
ubuntu@node-01:~$ sudo memray attach 9820 -o q
Failed to start tracking in remote process: OSError('Could not create output file /home/ubuntu/q: Permission denied')
ubuntu@node-01:~$ ls -al
total 36
drwxr-x--- 6 ubuntu ubuntu 4096 Aug 12 04:21 .
drwxr-xr-x 3 root   root   4096 Aug 11 23:46 ..
-rw-r--r-- 1 ubuntu ubuntu  220 Jan  6  2022 .bash_logout
-rw-r--r-- 1 ubuntu ubuntu 3771 Jan  6  2022 .bashrc
drwx------ 3 ubuntu ubuntu 4096 Aug 12 03:41 .cache
drwxrwxr-x 5 ubuntu ubuntu 4096 Aug 12 03:41 .env
drwxrwxr-x 4 ubuntu ubuntu 4096 Aug 12 03:44 .local
-rw-r--r-- 1 ubuntu ubuntu  807 Jan  6  2022 .profile
drwx------ 2 ubuntu ubuntu 4096 Aug 11 23:46 .ssh
-rw-r--r-- 1 ubuntu ubuntu    0 Aug 12 03:29 .sudo_as_admin_successful
-rw-r--r-- 1 root   root      0 Aug 12 03:47 q
`

**Comment by godlygeek** [comment]
Oh, wait - what user is process 9820 running as? The file gets opened by the process being attached _to_, not the process doing the attaching. You're running the file that's doing the attaching as root, but haven't shown what user the process being attached to is running as. If it's not the `ubuntu` user or the `root` user, it won't have privileges to write to the `ubuntu` user's home directory. Does this work?
```sh
sudo memray attach 9820 -o /tmp/q
```

**Comment by xtrusia** [comment]
oh right. it seems to be working. can I have a question? if there is proper q file. how I can use it? 

```sudo memray attach 9820 -o /tmp/q``` 

this just returned right away.. thanks a lot!

**Comment by godlygeek** [comment]
Glad you got it working!

You can stop tracking and flush the capture file with `sudo memray detach 9820`, and then parse the file with one of the memray reporters, like `memray summary /tmp/q` or `memray flamegraph /tmp/q` - see https://bloomberg.github.io/memray/summary.html and https://bloomberg.github.io/memray/flamegraph.html
