### ISSUE TITLE
Memory allocations with `???` location for gunicorn process running in docker

### ISSUE THREAD

**Issue by jaideep329** [bloomberg/memray#663]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Im trying to debug memory leak for a Django application which uses gunicorn. The process runs inside docker container. When i run `memray attach <pid>`, i do not see any memory allocations, just one entry with `???`:

![Screenshot 2024-08-09 at 5 30 36 PM](https://github.com/user-attachments/assets/13e1da17-42ee-4040-a3ef-62bf28a3502b)

When i add `-- native` to the command, then i am able to see the allocations but not without it:

![Screenshot 2024-08-09 at 5 31 25 PM](https://github.com/user-attachments/assets/52cae41d-eb21-44ed-8d2a-c3cecb5dc04e)

### Expected Behavior

Im able to see memory allocations properly in live mode using `memray attach <pid>` on my mac(running using gunicorn as well) which look something like:

![Screenshot 2024-08-09 at 5 26 59 PM](https://github.com/user-attachments/assets/501472cd-481b-4042-8ea4-a2e8205fe1f1)

I was expecting a similar view for my production environment.

### Steps To Reproduce

I'm running the gunicorn processes inside a docker container running with base python image from AWS(public.ecr.aws/ews-network/python:3.9.20230614). When i run `memray attach <pid>` on any gunicorn worker process i see no memory allocations being made, i just see a single entry with `???`.

### Memray Version

1.13.4

### Python Version

3.9

### Operating System

Linux

**Comment by pablogsal** [comment]
This is not a bug. In non-native mode, `memray` only tracks Python stack frames so if the allocation happens in a thread that doesn't have any Python code above it it will not be resolved and will be shown as `???`. When you pass `--native` then memray activates machinery that allows it to resolve the native location for that and therefore it doesn't show `???` anymore.

If you want to do this with `memray attach` you can do `memray attach --native`.

**Comment by pablogsal** [comment]
Check also https://github.com/bloomberg/memray/discussions/70#discussioncomment-2675361

**Comment by pablogsal** [comment]
If you think there is still something here and you want us to investigate further, you need to provide a self-contained reproducer
