### ISSUE TITLE
Release 1.14.0 is not signed

### ISSUE THREAD

**Issue by inglor** [bloomberg/memray#679]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Current 1.14.0 is not signed with PGP

### Expected Behavior

Expected release 1.14.0 to be signed with PGP

### Steps To Reproduce

1. Checkout git repo tag
2. Not signed with PGP the 1.14.0 tag

### Memray Version

1.14.0

### Python Version

3.12

### Operating System

Linux

**Comment by pablogsal** [comment]
I resigned the tag with my PGP key

![Screenshot 2024-09-10 at 09 45 57](https://github.com/user-attachments/assets/a12dc617-f746-4156-b750-d85884668934)

**Comment by inglor** [comment]
Thanks for quick reply!
