### ISSUE TITLE
Set logging interval for run command

### ISSUE THREAD

**Issue by wigging** [bloomberg/memray#68]
As I mentioned in the discussion linked below, it would be useful to set the logging interval for the run command. For example, to log memory usage every 5 seconds something like the following option could be implemented:

```
memray run --interval 5 file.py
```

### Discussed in https://github.com/bloomberg/memray/discussions/66

<div type='discussions-op-text'>

<sup>Originally posted by **wigging** April 29, 2022</sup>
I'm using Memray to profile the memory usage of a long running Python program. The bin file is several gigabytes and I'm starting to run out of storage space. I think if I set the logging interval to a longer duration, it would decrease the size of the bin file. But the run command does not have any options for setting the logging interval. How can set the logging interval and/or decrease the size of the bin file?</div>

**Comment by godlygeek** [comment]
> it would be useful to set the logging interval for the run command. For example, to log memory usage every 5 seconds

This doesn't seem possible to me, on a very fundamental level. The way Memray works is by capturing all allocations and deallocations that are performed - it doesn't have a sampling interval like you're picturing, it's a continuous process.

Memray is a tracing profiler, not a sampling profiler.

**Comment by godlygeek** [comment]
I suppose it would be possible to aggregate records in memory, though - if you're OK with losing some information about the total number of allocations and the total bytes allocated, we could set some interval (like 5s) and, each time the timer expires, output only the allocation records that were either

a) allocated during that 5s window and not freed during that 5s window, or
b) freed during that 5s window and not allocated during that 5s window.

That would be possible, with an ensuing loss of fidelity.

**Comment by godlygeek** [comment]
@pablogsal Is that what you were picturing?

**Comment by pablogsal** [comment]
> @pablogsal Is that what you were picturing?

No, I think @wigging was referring to the interval at which we log the RSS. 🤔

**Comment by wigging** [comment]
The [memory_profiler](https://github.com/pythonprofilers/memory_profiler) tool allows the user to set the interval (sampling period in seconds). For example, if I set the interval for memory_profiler to 5 seconds, it will log the memory usage of the python program every 5 seconds. This helps reduce the size of the log file for long running programs. I would like a similar feature for Memray while still being able to visualize how the memory is being allocated in the program.

**Comment by godlygeek** [comment]
`memory_profiler` is a sampling profiler, which is why that option makes sense for it.

Memray is a tracing profiler, which doesn't have a sampling interval - it tracks each allocation as it occurs, instead of periodically inspecting the state of the heap as a sampling profiler would.

**Comment by wigging** [comment]
Ok. Well I would like to use Memray for a long running Python program. The program runs for several hours and its memory usage gradually increases. But the log (bin file) that Memray produces for this program is huge, as in several gigabytes. I'm running it on a compute instance that has limited storage where large bin files quickly use up all the storage. So, I don't want to use Memray to profile the program for several hours. I just want Memray to profile it for something like 10 minutes at the beginning, middle, and end of the program's execution.

**Comment by wigging** [comment]
I could use the live reporting feature but I don't want to view the program for several hours.

**Comment by wigging** [comment]
The [Memray API](https://bloomberg.github.io/memray/api.html) discusses a `memory_interval_ms` parameter. Can that be implemented as a command line argument to set logging interval?

**Comment by godlygeek** [comment]
We could have a command line argument for that, but it wouldn't be useful to you.

That controls how often we write a 20 byte record to the output file that contains only the current timestamp and the current memory usage in bytes. That type of record is currently used only to populate a chart at the top of the HTML reports that shows how the process's total memory usage changed over time as the process was tracked. By default, that's written every 10ms, so 100 times per second, which costs 2000 bytes (2kb) per second. If your program runs for 60 minutes (3600 seconds), that records of that type account for only 7.2 mb of the data in your capture file. All of the rest of the data in the file comes from the captured allocation records, and there's currently no way to capture less data, or to write less of the captured data.

**Comment by wigging** [comment]
Ah, ok. Thanks for the explanation.

**Comment by godlygeek** [comment]
I'm going to close this. What you're asking for isn't something that we can easily provide because of the way that our profiler works. If you want to use Memray, you'll be best served by trying to make a smaller test case out of your application that runs for a shorter period of time, or operates on less data, and analyzing its memory usage as a representative sample of the actions taken by your full program.

If you can't do that and do need to watch the behavior of a long running process, a sampling profiler would probably fit your needs better than a tracing profiler does.

**Comment by godlygeek** [comment]
The new [aggregated capture file](https://bloomberg.github.io/memray/run.html#aggregated-capture-files) option introduced in Memray 1.7.0 should work as a very nice escape hatch for your use case, @cozos.

Check those docs out, and see if it works for your use case!

**Comment by cozos** [comment]
Thank you @godlygeek ! 👀
