### ISSUE TITLE
Can't get memray to output with AGGREGATED_ALLOCATIONS

### ISSUE THREAD

**Issue by sumeet-wisdom** [bloomberg/memray#680]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In my case of long running application, I never see anything written to output bin file
From the description, I understand that allocation records are written to bin file when heap memory high water mark is crossed. Maybe in my case, high water mark is not being reached. Is there a way to set the high water mark?

### Memray Version

latest

### Python Version

3.11

### Operating System

Linux

**Comment by godlygeek** [comment]
> From the description, I understand that allocation records are written to bin file when heap memory high water mark is crossed.

No, that's not correct. The `AGGREGATED_ALLOCATIONS` mode holds all of the statistics in memory while the profiled application runs, and only writes to the file when tracking ends. [The docs](https://bloomberg.github.io/memray/run.html#aggregated-capture-files) explain this caveat:

> Also, note that if the process is killed before tracking ends (for instance, by the Linux OOM killer), then the process will die before it finishes calculating its statistics, and so no useful information is ever written to the capture file. With the default file format, the capture file is usually still usable even if the process crashes or is killed, but with the aggregated file format it is not.

Either you need your long-running application to end, or you need to exit the `with` block if you're using the `Tracker` API.

**Comment by sumeet-wisdom** [comment]
> Either you need your long-running application to end, or you need to exit the `with` block if you're using the `Tracker` API.

Thank you. This got it working.
