### ISSUE TITLE
Sigkills and crashes when trying to profile a gunicorn process

### ISSUE THREAD

**Issue by hay** [bloomberg/memray#694]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Steps To Reproduce

I'm trying to run a Falcon app using a gunicorn process like this:

```bash
memray run -o test.bin ./env/bin/gunicorn -k gevent -w 1 -b 0.0.0.0:8082 services.webapi -e CONF_PATH=../etc/
```

The `services.webapi` is a typical implementation of a Falcon app. It runs fine without memray, but when i try to profile it i get this:

```bash
[2024-10-28 15:49:10 +0100] [82817] [INFO] Starting gunicorn 21.2.0
[2024-10-28 15:49:10 +0100] [82817] [INFO] Listening at: http://0.0.0.0:8082 (82817)
[2024-10-28 15:49:10 +0100] [82817] [INFO] Using worker: gevent
[2024-10-28 15:49:10 +0100] [82818] [INFO] Booting worker with pid: 82818
objc[82818]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called.
objc[82818]: +[__NSCFConstantString initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
[2024-10-28 15:49:10 +0100] [82817] [ERROR] Worker (pid:82818) was sent SIGKILL! Perhaps out of memory?
```

After that it just keeps crashing in a loop with the same error.

I've been trying to see if there's an import somewhere that might cause this, but it's a pretty big app so it's difficult to make a small usecase that always reproduces this error.

### Memray Version

1.14.0

### Python Version

3.10

### Operating System

macOS 14.6.1

**Comment by pablogsal** [comment]
Can you please provide a reproducer that we can run? Without it it's impossible to us to take a look at the problem

**Comment by hay** [comment]
Hey @pablogsal, i realise that you need more than just a command to debug, i could try to make something reproducable, but it's a big app so this might take some time.

However, the `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` seems to work and i can run the app fine now. Thanks!
