### ISSUE TITLE
docs: Screenshots of flame graph and table reporters don't include RSS graph

### ISSUE THREAD

**Issue by godlygeek** [bloomberg/memray#71]
Looks like the screenshots need to be updated for the new feature.

**Comment by sgibson19** [comment]
I would like to work on this issue

**Comment by gusmonod** [comment]
Hi @sgibson19 have you had time to look into this after all? It looks like the [flamegraph docs](https://bloomberg.github.io/memray/flamegraph.html) have screenshots that don't include those graphs, and although the [example docs](https://bloomberg.github.io/memray/examples/README.html) have generated flamegraphs with RSS graphs, they don't have the heap size line that was added by #142 

As far as I can tell, there is no documentation on how to read these lines and there were [two](https://github.com/bloomberg/memray/discussions/246) [questions](https://github.com/bloomberg/memray/discussions/273) about resident size vs heap size in the discussions already.

Maybe we could link to the [blog post](https://www.baeldung.com/linux/resident-set-vs-virtual-memory-size) that [pablo mentioned](https://github.com/bloomberg/memray/discussions/273#discussioncomment-4390748)?

**Comment by sgibson19** [comment]
Hi @gusmonod I just started to look into it. Looking through the docs right now

**Comment by drz416** [comment]
I will look into this today.

**Comment by drz416** [comment]
This can be closed now.
