### ISSUE TITLE
Memray seems to modify sys.path such that local module imports fail

### ISSUE THREAD

**Issue by ethteck** [bloomberg/memray#76]
## Bug Report

My script has a line as such:
`from segtypes.segment import Segment`
where segtypes.segment is a module in the current directory. Memray seems to modify the sys.path such that the cwd is not included in the list, whereas it is included during a normal python invocation. Unless I manually append the cwd to sys.path, the import fails.

```
Traceback (most recent call last):
  File "/home/ethteck/.local/bin/memray", line 8, in <module>
    sys.exit(main())
  File "/home/ethteck/.local/lib/python3.10/site-packages/memray/commands/__init__.py", line 124, in main
    arg_values.entrypoint(arg_values, parser)
  File "/home/ethteck/.local/lib/python3.10/site-packages/memray/commands/run.py", line 260, in run
    _run_with_file_output(args)
  File "/home/ethteck/.local/lib/python3.10/site-packages/memray/commands/run.py", line 152, in _run_with_file_output
    _run_tracker(
  File "/home/ethteck/.local/lib/python3.10/site-packages/memray/commands/run.py", line 55, in _run_tracker
    runpy.run_path(args.script, run_name="__main__")
  File "/usr/lib/python3.10/runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/usr/lib/python3.10/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "split.py", line 10, in <module>
    from segtypes.segment import Segment
ModuleNotFoundError: No module named 'segtypes'
```

**Input Code**

- REPL or Repo link if applicable: https://github.com/ethteck/splat
`memray run -o output.bin split.py`

**Expected behavior/code** A clear and concise description of what you expected to happen (or
code).
No ModuleNotFoundError s

**Environment**

- Python(s): Python 3.10.4

**Comment by godlygeek** [comment]
Hm, yeah - the interpreter would normally automatically put the directory containing `split.py` at the start of `sys.path`, and instead it's automatically putting the directory containing `memray` at the start of `sys.path` when you start the interpreter with `memray`.

That shouldn't be too much work to fix, I think...

**Comment by ethteck** [comment]
Thank you!

**Comment by julhac** [comment]
I am working in an environment

`julhac:~/env_name$ .venv/bin/python3.10 -m memray run "src/flows/code.py"`

and still get this error (code.py imports src)

ModuleNotFoundError: No module named 'src'

What's the issue?

**Comment by godlygeek** [comment]
That should fail without Memray, too, if you just run

`.venv/bin/python3.10 "src/flows/code.py"`

That's because the interpreter puts the directory containing the file you run on `sys.path`, rather than your current working directory. If you need the current working directory on your path, it should work to run

`PYTHONPATH=. .venv/bin/python3.10 "src/flows/code.py"`

without Memray, and

`PYTHONPATH=. .venv/bin/python3.10 -m memray run "src/flows/code.py"`

with Memray.

**Comment by julhac** [comment]
You're totally right! With `PYTHONPATH=.` it does work.
Thank you so much for the prompt response!
