### ISSUE TITLE
Information about which allocator was used is lost in roll-up

### ISSUE THREAD

**Issue by godlygeek** [bloomberg/memray#85]
Consider this code:

```py
import mmap

for i in range(5):
    x = mmap.mmap(-1, 10000000000) if i == 0 else "x" * 1000000
```

This is what we currently show in the `stats` reporter:

```
📏 Total allocations:
        21

📦 Total memory allocated:
        9.314GB

📊 Histogram of allocation size:
        min: 528.000B
        ----------------------------------------
        < 2.754KB  : 8 ▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇▇
        < 14.717KB : 2 ▇▇▇▇▇▇▇
        < 78.624KB : 0
        < 420.047KB: 0
        < 2.191MB  : 0
        < 11.708MB : 0
        < 62.549MB : 0
        < 334.166MB: 0
        < 1.743GB  : 0
        <=9.314GB  : 1 ▇▇▇▇
        ----------------------------------------
        max: 9.314GB

📂 Allocator type distribution:
         MALLOC: 11
```

The allocator type distribution is incorrect - it says there were no MMAP allocations and only MALLOC allocations. The fact that different types of allocations occurred on the same line is being lost.

**Comment by godlygeek** [comment]
Also - the fact that "📂 Allocator type distribution:" shows 11 allocations and "📏 Total allocations:" shows 21 seems suspicious... is free() being counted as an allocation?

**Comment by pablogsal** [comment]
> Also - the fact that "📂 Allocator type distribution:" shows 11 allocations and "📏 Total allocations:" shows 21 seems suspicious... is free() being counted as an allocation?

No, it is taking into account how many allocations have been aggregated into the same place IIRC.

**Comment by pablogsal** [comment]
> The fact that different types of allocations occurred on the same line is being lost.

That happens because we aggregate all allocations that happen in the same place together and indeed if multiple allocators are used this information is lost.
